# Generated by Django 4.2.1 on 2023-05-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='frirst_name',
            new_name='first_name',
        ),
    ]
